baseURL = "https://nothinbutscores.com/"
languageCode = "en-us"
title = "Nothin But Scores"
pluralizelisttitles = false

[params]
info = "Follow your teams without all the noise."
secondaryinfo = "Find your favorite teams on Twitter now."

[[menu.main]]
    name = "NBA"
    weight = 2
    url = "/nba/"
[[menu.main]]
    name = "PGA"
    weight = 3
    url  = "/pga/"
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"